---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-standalone
spec:
  serviceName: mysql-standalone
  replicas: 1 # Increasing this will NOT of course make MySQL HA!
  selector:
    matchLabels:
      app: mysql-standalone
  template:
    metadata:
      labels:
        app: mysql-standalone
    spec:
      containers:
        - name: mysql-standalone
          image: mysql@sha256:53ca64a889514c294b85d003de4de35098734a025c776d659fc75ae23a63f5c4
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-standalone-secrets
                  key: rootPassword
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-standalone
  labels:
    app: mysql-standalone
spec:
  selector:
    app: mysql-standalone
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  # phpMyAdmin session handling is not really compatible with more replicas
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin@sha256:caf285a9d9ba1b9b1daa6ec63a0290a1ef743d7d32300d15a56c487dcd418353
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          env:
            - name: PMA_HOSTS
              value: mysql-standalone
            - name: PMA_PORTS
              value: "3306"
            - name: PMA_ABSOLUTE_URI
              value: https://phpmyadmin-laurivosandi.codemowers.ee/
            - name: UPLOAD_LIMIT
              value: 10G
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin
  annotations:
    kubernetes.io/ingress.class: shared
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: traefik.codemowers.ee
spec:
  rules:
    - host: phpmyadmin-laurivosandi.codemowers.ee
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: phpmyadmin
                port:
                  number: 80
  tls:
    - hosts:
        - "*.codemowers.ee"
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
